// Flat ESLint config. Type-checking stays the job of `tsc --noEmit` (the `lint`
// script); ESLint adds style/quality rules on top.
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import reactHooks from "eslint-plugin-react-hooks";

export default tseslint.config(
  {
    ignores: [
      "**/dist/**",
      "**/node_modules/**",
      "**/target/**",
      "**/.turbo/**",
      // Generated by wasm-bindgen (build-burn-cnn.sh); do not hand-edit.
      "packages/playground/src/burn/pkg/**",
      "**/coverage/**",
      "pnpm-lock.yaml",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ["**/*.{ts,tsx,mts,mjs,js,jsx}"],
    rules: {
      // The codebase uses explicit `any` deliberately at worker/protocol and
      // test-double boundaries. `noImplicitAny` + tsc strict already guard the
      // implicit cases.
      "@typescript-eslint/no-explicit-any": "off",
      // tsc's `noUnusedLocals`/`noUnusedParameters` already enforce this.
      "@typescript-eslint/no-unused-vars": "off",
      // `{}` / empty interface types appear in a few loose protocol seams.
      "@typescript-eslint/no-empty-object-type": "off",
      // The ported network engine (nn.ts) intentionally merges an interface and
      // a class with the same name (e.g. RegularizationFunction) — the class is a
      // namespace for static presets, the interface describes their shape.
      "@typescript-eslint/no-unsafe-declaration-merging": "off",
    },
  },
  {
    files: ["**/*.{ts,tsx,js,jsx}"],
    plugins: { "react-hooks": reactHooks },
    rules: {
      "react-hooks/rules-of-hooks": "error",
      // `warn` (not error) so existing intentional `// eslint-disable` spots keep
      // working and CI isn't blocked; new violations surface as warnings.
      "react-hooks/exhaustive-deps": "warn",
    },
  },
);
