export {
  computeSectionLayout,
  SectionRegistry,
  SectionStore,
  sortSections,
} from "./section";
export type {
  SectionDefinition,
  SectionLayoutOptions,
  SectionLayoutResult,
  SectionRect,
  SectionSize,
  SectionState,
  SectionStoreSnapshot,
} from "./section";

export { downsample, extent } from "./utils/math";

export {
  ACTIVATIONS,
  DATASETS,
  DEFAULT_CONFIG,
  OPTIMIZERS,
  PLAYGROUND_PRESETS,
  advanceLiveTraining,
  buildPayload,
  createLiveTrainingState,
  createMLP,
  frameIndexForEpoch,
  gridForEpoch,
  makeDataset,
  resetLiveTraining,
  configSignature,
  DEFAULT_CNN_CONFIG,
  DEFAULT_CNN_CONFIG_2D,
  DEFAULT_CNN_CONFIG_1D,
  CNN_DATASET_IDS_2D,
  CNN_DATASET_IDS_1D,
  CNN_ACTIVATION_IDS,
  CNN_REGULARIZATIONS,
  CNN_REGULARIZATION_RATES,
  PLAYGROUND_OPTIMIZERS,
  IMAGE_SIZE,
  IMAGE_SIZE_THREE_FOUR_LOOPS,
  imageSizeForDataset,
  SIGNAL_LENGTH,
  TrainWorkerClient,
  canUseTrainWorkers,
  makeImageDataset,
  makeSignalDataset,
} from "./playground";
export type {
  ActivationId,
  BoundarySnapshot,
  DatasetId,
  FeatureName,
  GridPoint,
  HistoryRow,
  LiveTrainingState,
  OptimizerId,
  PlaygroundConfig,
  PlaygroundOptimizerId,
  PlaygroundPayload,
  Sample,
  CnnMode,
  LayerSpec,
  CnnConfig,
  CnnTrainingStats,
  FeatureMapSnapshot,
  ImageExample,
  SignalExample,
  CnnDatasetId,
  CnnDatasetId2D,
  CnnDatasetId1D,
  CnnActivationId,
  CnnRegularizationId,
  LayerKind,
  LayerShape,
  Map2D,
  Volume,
  CnnSignal,
  CnnLayerView,
  CnnTrainSnapshot,
  NetworkTrainSnapshot,
  MlpTrainSnapshot,
  TrainSnapshot,
  ToTrainWorker,
  FromTrainWorker,
  TrainRebuildReason,
  TrainWorkerClientOptions,
  TrainWorkerTickHandler,
  TrainWorkerErrorHandler,
} from "./playground";

export {
  addSignals,
  buildSignal,
  convolve,
  convolveViaFft,
  correlate,
  defaultSignalParams,
  dftMagnitude,
  fft,
  fftRadix2,
  getSignalPresetSpec,
  ifft,
  makeComplex,
  makeSignal,
  nextPow2,
  SIGNAL_PRESET_IDS,
  SIGNAL_PRESETS,
  toComplex,
  zeros,
} from "./signal";
export type {
  ComplexArray,
  ConvolutionViaFftResult,
  Signal,
  SignalParamId,
  SignalParamSpec,
  SignalParams,
  SignalPresetId,
  SignalPresetSpec,
  Spectrum,
} from "./signal";

export { SignalPlot } from "./charts/signal-plot";
export type { SignalMarker, SignalPlotSeries, SignalPlotPayload } from "./charts/signal-plot";

export { DecisionBoundaryPlot } from "./charts/decision-boundary-plot";
export type { DecisionBoundaryPayload } from "./charts/decision-boundary-plot";

export { reduceMatrix, renderValueMatrix } from "./charts/mini-heatmap";
export type {
  RenderValueMatrixOptions,
  ValueMatrixLayout,
  ValueMatrixPalette,
} from "./charts/mini-heatmap";
export {
  curveStrokeFromValues,
  inferYDomain,
  renderCurve,
  renderCurvePoints,
  renderTargetCurve,
} from "./charts/mini-curve";

export {
  Activations,
  backProp,
  boundaryToGridPoints,
  buildNetwork,
  classifyCircleData,
  classifySpiralData,
  classifyTwoGaussData,
  classifyXORData,
  CLASS_0_HEX,
  CLASS_1_HEX,
  computeBoundaries,
  constructInput,
  constructInputIds,
  CURVE_DENSITY,
  DATASETS as NETWORK_DATASETS,
  DATASETS_1D as NETWORK_DATASETS_1D,
  DATASETS_1D_CLASSIFICATION as NETWORK_DATASETS_1D_CLASSIFICATION,
  DATASETS_1D_REGRESSION as NETWORK_DATASETS_1D_REGRESSION,
  DATASETS_2D_CLASSIFICATION as NETWORK_DATASETS_2D_CLASSIFICATION,
  DATASETS_2D_REGRESSION as NETWORK_DATASETS_2D_REGRESSION,
  DEFAULT_NETWORK_CONFIG,
  DENSITY,
  FEATURES_1D,
  FEATURES_2D_ONLY,
  isDataset1DId,
  isDataset1DClassificationId,
  isDataset1DRegressionId,
  isDataset2DClassificationId,
  isDataset2DRegressionId,
  NODE_BOUNDARY_DENSITY,
  NODE_CURVE_DENSITY,
  PLAY_DISPLAY_DENSITY,
  Errors,
  examplesToSamples,
  forwardProp,
  forEachNode,
  getOutputNode,
  INPUT_IDS,
  INPUTS,
  Link,
  Node,
  NUM_SAMPLES,
  PlaygroundEngine,
  RegularizationFunction,
  shuffle,
  NETWORK_ACTIVATIONS,
  NETWORK_REGULARIZATIONS,
  NETWORK_REGULARIZATION_RATES,
  WEIGHT_INITS,
  updateWeights,
  valueToRgb,
  weightColor,
  weightColorQuantized,
  weightMagnitude,
  weightValueNormalized,
  X_DOMAIN,
  applyArchitecturePreset,
  backPropGraph,
  buildMlpGraph,
  buildMiniResNetGraph,
  buildResBlockGraph,
  ComputationalGraph,
  computeGraphBoundaries,
  forwardPropGraph,
  forEachGraphNode,
  GraphNode,
  layoutMlpFromLayers,
  MLP_COL_SPACING,
  MLP_NODE_SIZE,
  MLP_OUTPUT_NODE_SIZE,
  normalizeGraphLayout,
  PALETTE_NODE_KINDS,
  presetLabel,
  updateWeightsGraph,
} from "./playground/network";
export type {
  ArchitecturePresetId,
  DataGenerator as NetworkDataGenerator,
  Dataset1DClassificationId,
  Dataset1DId,
  Dataset1DRegressionId,
  Dataset2DClassificationId,
  Dataset2DRegressionId,
  DatasetId as NetworkDatasetId,
  Example2D,
  GraphEdgeDef,
  GraphNodeKind,
  GraphPosition,
  GraphSnapshot,
  InputFeature,
  LossHistoryPoint,
  PaletteNodeKind,
  NetworkActivationId,
  NetworkAnyDatasetId,
  NetworkDataMode,
  NetworkPlaygroundConfig,
  NetworkProblemType,
  NetworkRegularizationId,
  WeightInitId,
} from "./playground/network";

export {
  AutogradGraph,
  AutogradNode,
  AutogradEdge,
  AUTOGRAD_PALETTE_OPS,
  AUTOGRAD_PRESETS,
  buildAutogradPreset,
  CompGraphEngine,
  DEFAULT_COMPGRAPH_CONFIG,
  evaluateOp,
  localDerivatives,
  OP_SPECS,
  resetAutogradIdCounter,
} from "./playground/autograd";
export type {
  AutogradEdgeDef,
  AutogradNodeDef,
  AutogradOp,
  AutogradPosition,
  AutogradPresetId,
  AutogradSnapshot,
  CompGraphConfig,
  OpSpec,
} from "./playground/autograd";

export {
  coreMessages,
  getLocale,
  localeLabels,
  locales,
  setLocale,
  subscribeLocale,
  t,
} from "./i18n";
export type { CoreMessages, Locale } from "./i18n";
