/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmcnnengine_free: (a: number, b: number) => void;
export const wasmcnnengine_accumulateBatch: (a: number, b: number, c: number) => number;
export const wasmcnnengine_addGradSums: (a: number, b: number, c: number) => void;
export const wasmcnnengine_applyConfigJson: (a: number, b: number, c: number) => [number, number];
export const wasmcnnengine_applySgd: (a: number, b: number, c: number) => void;
export const wasmcnnengine_backend: (a: number) => [number, number];
export const wasmcnnengine_bumpEpoch: (a: number, b: number) => void;
export const wasmcnnengine_configJson: (a: number) => [number, number, number, number];
export const wasmcnnengine_create: (a: number, b: number) => any;
export const wasmcnnengine_epoch: (a: number) => number;
export const wasmcnnengine_exportGrads: (a: number) => [number, number];
export const wasmcnnengine_exportParams: (a: number) => [number, number];
export const wasmcnnengine_featureMaps: (a: number, b: number) => [number, number, number];
export const wasmcnnengine_inspected: (a: number) => number;
export const wasmcnnengine_loadParams: (a: number, b: number, c: number) => void;
export const wasmcnnengine_lossHistory: (a: number) => [number, number, number];
export const wasmcnnengine_metas: (a: number) => [number, number, number];
export const wasmcnnengine_nTrain: (a: number) => number;
export const wasmcnnengine_new: (a: number, b: number) => [number, number, number];
export const wasmcnnengine_paramCount: (a: number) => number;
export const wasmcnnengine_predictGallery: (a: number, b: number) => [number, number, number];
export const wasmcnnengine_probability: (a: number) => number;
export const wasmcnnengine_pushLossHistory: (a: number) => void;
export const wasmcnnengine_rebuildModel: (a: number) => void;
export const wasmcnnengine_refreshAccuracy: (a: number) => void;
export const wasmcnnengine_refreshMetrics: (a: number) => void;
export const wasmcnnengine_setData1d: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const wasmcnnengine_setData2d: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const wasmcnnengine_setInspected: (a: number, b: number) => void;
export const wasmcnnengine_stats: (a: number) => [number, number, number];
export const wasmcnnengine_trainEpoch: (a: number) => void;
export const wasmcnnengine_trainEpochRecord: (a: number) => [number, number, number];
export const wasmcnnengine_zeroAllGrads: (a: number) => void;
export const wasm_bindgen_af390c650355dc71___convert__closures_____invoke___wasm_bindgen_af390c650355dc71___JsValue__core_9b3796e30d99ddb7___result__Result_____wasm_bindgen_af390c650355dc71___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_af390c650355dc71___convert__closures_____invoke___js_sys_5151b4f7262fa7a5___Function_fn_wasm_bindgen_af390c650355dc71___JsValue_____wasm_bindgen_af390c650355dc71___sys__Undefined___js_sys_5151b4f7262fa7a5___Function_fn_wasm_bindgen_af390c650355dc71___JsValue_____wasm_bindgen_af390c650355dc71___sys__Undefined_______true_: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
